/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_V1_ESP8266_PB_H_INCLUDED
#define PB_V1_ESP8266_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _v1_DataRequest {
    uint32_t adc;
} v1_DataRequest;

typedef struct _v1_DataResponse {
    int32_t status;
} v1_DataResponse;


/* Initializer values for message structs */
#define v1_DataRequest_init_default              {0}
#define v1_DataResponse_init_default             {0}
#define v1_DataRequest_init_zero                 {0}
#define v1_DataResponse_init_zero                {0}

/* Field tags (for use in manual encoding/decoding) */
#define v1_DataRequest_adc_tag                   1
#define v1_DataResponse_status_tag               1

/* Struct field encoding specification for nanopb */
#define v1_DataRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adc,               1)
#define v1_DataRequest_CALLBACK NULL
#define v1_DataRequest_DEFAULT NULL

#define v1_DataResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    status,            1)
#define v1_DataResponse_CALLBACK NULL
#define v1_DataResponse_DEFAULT NULL

extern const pb_msgdesc_t v1_DataRequest_msg;
extern const pb_msgdesc_t v1_DataResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define v1_DataRequest_fields &v1_DataRequest_msg
#define v1_DataResponse_fields &v1_DataResponse_msg

/* Maximum encoded size of messages (where known) */
#define v1_DataRequest_size                      6
#define v1_DataResponse_size                     11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
