/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "user.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(v1_User, v1_User, AUTO)


PB_BIND(v1_UserResponse, v1_UserResponse, AUTO)


PB_BIND(v1_UsersResponse, v1_UsersResponse, AUTO)



