/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "google/protobuf/api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_Api, google_protobuf_Api, AUTO)


PB_BIND(google_protobuf_Method, google_protobuf_Method, AUTO)


PB_BIND(google_protobuf_Mixin, google_protobuf_Mixin, AUTO)



