/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_DESCRIPTOR_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_DESCRIPTOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _google_protobuf_FieldDescriptorProto_Type {
    google_protobuf_FieldDescriptorProto_Type_TYPE_DOUBLE = 1,
    google_protobuf_FieldDescriptorProto_Type_TYPE_FLOAT = 2,
    google_protobuf_FieldDescriptorProto_Type_TYPE_INT64 = 3,
    google_protobuf_FieldDescriptorProto_Type_TYPE_UINT64 = 4,
    google_protobuf_FieldDescriptorProto_Type_TYPE_INT32 = 5,
    google_protobuf_FieldDescriptorProto_Type_TYPE_FIXED64 = 6,
    google_protobuf_FieldDescriptorProto_Type_TYPE_FIXED32 = 7,
    google_protobuf_FieldDescriptorProto_Type_TYPE_BOOL = 8,
    google_protobuf_FieldDescriptorProto_Type_TYPE_STRING = 9,
    google_protobuf_FieldDescriptorProto_Type_TYPE_GROUP = 10,
    google_protobuf_FieldDescriptorProto_Type_TYPE_MESSAGE = 11,
    google_protobuf_FieldDescriptorProto_Type_TYPE_BYTES = 12,
    google_protobuf_FieldDescriptorProto_Type_TYPE_UINT32 = 13,
    google_protobuf_FieldDescriptorProto_Type_TYPE_ENUM = 14,
    google_protobuf_FieldDescriptorProto_Type_TYPE_SFIXED32 = 15,
    google_protobuf_FieldDescriptorProto_Type_TYPE_SFIXED64 = 16,
    google_protobuf_FieldDescriptorProto_Type_TYPE_SINT32 = 17,
    google_protobuf_FieldDescriptorProto_Type_TYPE_SINT64 = 18
} google_protobuf_FieldDescriptorProto_Type;

typedef enum _google_protobuf_FieldDescriptorProto_Label {
    google_protobuf_FieldDescriptorProto_Label_LABEL_OPTIONAL = 1,
    google_protobuf_FieldDescriptorProto_Label_LABEL_REQUIRED = 2,
    google_protobuf_FieldDescriptorProto_Label_LABEL_REPEATED = 3
} google_protobuf_FieldDescriptorProto_Label;

typedef enum _google_protobuf_FileOptions_OptimizeMode {
    google_protobuf_FileOptions_OptimizeMode_SPEED = 1,
    google_protobuf_FileOptions_OptimizeMode_CODE_SIZE = 2,
    google_protobuf_FileOptions_OptimizeMode_LITE_RUNTIME = 3
} google_protobuf_FileOptions_OptimizeMode;

typedef enum _google_protobuf_FieldOptions_CType {
    google_protobuf_FieldOptions_CType_STRING = 0,
    google_protobuf_FieldOptions_CType_CORD = 1,
    google_protobuf_FieldOptions_CType_STRING_PIECE = 2
} google_protobuf_FieldOptions_CType;

typedef enum _google_protobuf_FieldOptions_JSType {
    google_protobuf_FieldOptions_JSType_JS_NORMAL = 0,
    google_protobuf_FieldOptions_JSType_JS_STRING = 1,
    google_protobuf_FieldOptions_JSType_JS_NUMBER = 2
} google_protobuf_FieldOptions_JSType;

typedef enum _google_protobuf_MethodOptions_IdempotencyLevel {
    google_protobuf_MethodOptions_IdempotencyLevel_IDEMPOTENCY_UNKNOWN = 0,
    google_protobuf_MethodOptions_IdempotencyLevel_NO_SIDE_EFFECTS = 1,
    google_protobuf_MethodOptions_IdempotencyLevel_IDEMPOTENT = 2
} google_protobuf_MethodOptions_IdempotencyLevel;

/* Struct definitions */
typedef struct _google_protobuf_ExtensionRangeOptions {
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_ExtensionRangeOptions;

typedef struct _google_protobuf_FileDescriptorSet {
    pb_callback_t file;
} google_protobuf_FileDescriptorSet;

typedef struct _google_protobuf_GeneratedCodeInfo {
    pb_callback_t annotation;
} google_protobuf_GeneratedCodeInfo;

typedef struct _google_protobuf_OneofOptions {
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_OneofOptions;

typedef struct _google_protobuf_SourceCodeInfo {
    pb_callback_t location;
} google_protobuf_SourceCodeInfo;

typedef struct _google_protobuf_SourceCodeInfo_Location {
    pb_callback_t path;
    pb_callback_t span;
    pb_callback_t leading_comments;
    pb_callback_t trailing_comments;
    pb_callback_t leading_detached_comments;
} google_protobuf_SourceCodeInfo_Location;

typedef struct _google_protobuf_DescriptorProto_ExtensionRange {
    bool has_start;
    int32_t start;
    bool has_end;
    int32_t end;
    bool has_options;
    google_protobuf_ExtensionRangeOptions options;
} google_protobuf_DescriptorProto_ExtensionRange;

typedef struct _google_protobuf_DescriptorProto_ReservedRange {
    bool has_start;
    int32_t start;
    bool has_end;
    int32_t end;
} google_protobuf_DescriptorProto_ReservedRange;

typedef struct _google_protobuf_EnumDescriptorProto_EnumReservedRange {
    bool has_start;
    int32_t start;
    bool has_end;
    int32_t end;
} google_protobuf_EnumDescriptorProto_EnumReservedRange;

typedef struct _google_protobuf_EnumOptions {
    bool has_allow_alias;
    bool allow_alias;
    bool has_deprecated;
    bool deprecated;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_EnumOptions;

typedef struct _google_protobuf_EnumValueOptions {
    bool has_deprecated;
    bool deprecated;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_EnumValueOptions;

typedef struct _google_protobuf_FieldOptions {
    bool has_ctype;
    google_protobuf_FieldOptions_CType ctype;
    bool has_packed;
    bool packed;
    bool has_deprecated;
    bool deprecated;
    bool has_lazy;
    bool lazy;
    bool has_jstype;
    google_protobuf_FieldOptions_JSType jstype;
    bool has_weak;
    bool weak;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_FieldOptions;

typedef struct _google_protobuf_FileOptions {
    pb_callback_t java_package;
    pb_callback_t java_outer_classname;
    bool has_optimize_for;
    google_protobuf_FileOptions_OptimizeMode optimize_for;
    bool has_java_multiple_files;
    bool java_multiple_files;
    pb_callback_t go_package;
    bool has_cc_generic_services;
    bool cc_generic_services;
    bool has_java_generic_services;
    bool java_generic_services;
    bool has_py_generic_services;
    bool py_generic_services;
    bool has_java_generate_equals_and_hash;
    bool java_generate_equals_and_hash;
    bool has_deprecated;
    bool deprecated;
    bool has_java_string_check_utf8;
    bool java_string_check_utf8;
    bool has_cc_enable_arenas;
    bool cc_enable_arenas;
    pb_callback_t objc_class_prefix;
    pb_callback_t csharp_namespace;
    pb_callback_t swift_prefix;
    pb_callback_t php_class_prefix;
    pb_callback_t php_namespace;
    bool has_php_generic_services;
    bool php_generic_services;
    pb_callback_t php_metadata_namespace;
    pb_callback_t ruby_package;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_FileOptions;

typedef struct _google_protobuf_GeneratedCodeInfo_Annotation {
    pb_callback_t path;
    pb_callback_t source_file;
    bool has_begin;
    int32_t begin;
    bool has_end;
    int32_t end;
} google_protobuf_GeneratedCodeInfo_Annotation;

typedef struct _google_protobuf_MessageOptions {
    bool has_message_set_wire_format;
    bool message_set_wire_format;
    bool has_no_standard_descriptor_accessor;
    bool no_standard_descriptor_accessor;
    bool has_deprecated;
    bool deprecated;
    bool has_map_entry;
    bool map_entry;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_MessageOptions;

typedef struct _google_protobuf_MethodOptions {
    bool has_deprecated;
    bool deprecated;
    bool has_idempotency_level;
    google_protobuf_MethodOptions_IdempotencyLevel idempotency_level;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_MethodOptions;

typedef struct _google_protobuf_OneofDescriptorProto {
    pb_callback_t name;
    bool has_options;
    google_protobuf_OneofOptions options;
} google_protobuf_OneofDescriptorProto;

typedef struct _google_protobuf_ServiceOptions {
    bool has_deprecated;
    bool deprecated;
    pb_callback_t uninterpreted_option;
    pb_extension_t *extensions;
} google_protobuf_ServiceOptions;

typedef struct _google_protobuf_UninterpretedOption {
    pb_callback_t name;
    pb_callback_t identifier_value;
    bool has_positive_int_value;
    uint64_t positive_int_value;
    bool has_negative_int_value;
    int64_t negative_int_value;
    bool has_double_value;
    double double_value;
    pb_callback_t string_value;
    pb_callback_t aggregate_value;
} google_protobuf_UninterpretedOption;

typedef struct _google_protobuf_UninterpretedOption_NamePart {
    pb_callback_t name_part;
    bool is_extension;
} google_protobuf_UninterpretedOption_NamePart;

typedef struct _google_protobuf_DescriptorProto {
    pb_callback_t name;
    pb_callback_t field;
    pb_callback_t nested_type;
    pb_callback_t enum_type;
    pb_callback_t extension_range;
    pb_callback_t extension;
    bool has_options;
    google_protobuf_MessageOptions options;
    pb_callback_t oneof_decl;
    pb_callback_t reserved_range;
    pb_callback_t reserved_name;
} google_protobuf_DescriptorProto;

typedef struct _google_protobuf_EnumDescriptorProto {
    pb_callback_t name;
    pb_callback_t value;
    bool has_options;
    google_protobuf_EnumOptions options;
    pb_callback_t reserved_range;
    pb_callback_t reserved_name;
} google_protobuf_EnumDescriptorProto;

typedef struct _google_protobuf_EnumValueDescriptorProto {
    pb_callback_t name;
    bool has_number;
    int32_t number;
    bool has_options;
    google_protobuf_EnumValueOptions options;
} google_protobuf_EnumValueDescriptorProto;

typedef struct _google_protobuf_FieldDescriptorProto {
    pb_callback_t name;
    pb_callback_t extendee;
    bool has_number;
    int32_t number;
    bool has_label;
    google_protobuf_FieldDescriptorProto_Label label;
    bool has_type;
    google_protobuf_FieldDescriptorProto_Type type;
    pb_callback_t type_name;
    pb_callback_t default_value;
    bool has_options;
    google_protobuf_FieldOptions options;
    bool has_oneof_index;
    int32_t oneof_index;
    pb_callback_t json_name;
} google_protobuf_FieldDescriptorProto;

typedef struct _google_protobuf_FileDescriptorProto {
    pb_callback_t name;
    pb_callback_t package;
    pb_callback_t dependency;
    pb_callback_t message_type;
    pb_callback_t enum_type;
    pb_callback_t service;
    pb_callback_t extension;
    bool has_options;
    google_protobuf_FileOptions options;
    bool has_source_code_info;
    google_protobuf_SourceCodeInfo source_code_info;
    pb_callback_t public_dependency;
    pb_callback_t weak_dependency;
    pb_callback_t syntax;
} google_protobuf_FileDescriptorProto;

typedef struct _google_protobuf_MethodDescriptorProto {
    pb_callback_t name;
    pb_callback_t input_type;
    pb_callback_t output_type;
    bool has_options;
    google_protobuf_MethodOptions options;
    bool has_client_streaming;
    bool client_streaming;
    bool has_server_streaming;
    bool server_streaming;
} google_protobuf_MethodDescriptorProto;

typedef struct _google_protobuf_ServiceDescriptorProto {
    pb_callback_t name;
    pb_callback_t method;
    bool has_options;
    google_protobuf_ServiceOptions options;
} google_protobuf_ServiceDescriptorProto;


/* Helper constants for enums */
#define _google_protobuf_FieldDescriptorProto_Type_MIN google_protobuf_FieldDescriptorProto_Type_TYPE_DOUBLE
#define _google_protobuf_FieldDescriptorProto_Type_MAX google_protobuf_FieldDescriptorProto_Type_TYPE_SINT64
#define _google_protobuf_FieldDescriptorProto_Type_ARRAYSIZE ((google_protobuf_FieldDescriptorProto_Type)(google_protobuf_FieldDescriptorProto_Type_TYPE_SINT64+1))

#define _google_protobuf_FieldDescriptorProto_Label_MIN google_protobuf_FieldDescriptorProto_Label_LABEL_OPTIONAL
#define _google_protobuf_FieldDescriptorProto_Label_MAX google_protobuf_FieldDescriptorProto_Label_LABEL_REPEATED
#define _google_protobuf_FieldDescriptorProto_Label_ARRAYSIZE ((google_protobuf_FieldDescriptorProto_Label)(google_protobuf_FieldDescriptorProto_Label_LABEL_REPEATED+1))

#define _google_protobuf_FileOptions_OptimizeMode_MIN google_protobuf_FileOptions_OptimizeMode_SPEED
#define _google_protobuf_FileOptions_OptimizeMode_MAX google_protobuf_FileOptions_OptimizeMode_LITE_RUNTIME
#define _google_protobuf_FileOptions_OptimizeMode_ARRAYSIZE ((google_protobuf_FileOptions_OptimizeMode)(google_protobuf_FileOptions_OptimizeMode_LITE_RUNTIME+1))

#define _google_protobuf_FieldOptions_CType_MIN google_protobuf_FieldOptions_CType_STRING
#define _google_protobuf_FieldOptions_CType_MAX google_protobuf_FieldOptions_CType_STRING_PIECE
#define _google_protobuf_FieldOptions_CType_ARRAYSIZE ((google_protobuf_FieldOptions_CType)(google_protobuf_FieldOptions_CType_STRING_PIECE+1))

#define _google_protobuf_FieldOptions_JSType_MIN google_protobuf_FieldOptions_JSType_JS_NORMAL
#define _google_protobuf_FieldOptions_JSType_MAX google_protobuf_FieldOptions_JSType_JS_NUMBER
#define _google_protobuf_FieldOptions_JSType_ARRAYSIZE ((google_protobuf_FieldOptions_JSType)(google_protobuf_FieldOptions_JSType_JS_NUMBER+1))

#define _google_protobuf_MethodOptions_IdempotencyLevel_MIN google_protobuf_MethodOptions_IdempotencyLevel_IDEMPOTENCY_UNKNOWN
#define _google_protobuf_MethodOptions_IdempotencyLevel_MAX google_protobuf_MethodOptions_IdempotencyLevel_IDEMPOTENT
#define _google_protobuf_MethodOptions_IdempotencyLevel_ARRAYSIZE ((google_protobuf_MethodOptions_IdempotencyLevel)(google_protobuf_MethodOptions_IdempotencyLevel_IDEMPOTENT+1))


/* Initializer values for message structs */
#define google_protobuf_FileDescriptorSet_init_default {{{NULL}, NULL}}
#define google_protobuf_FileDescriptorProto_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_FileOptions_init_default, false, google_protobuf_SourceCodeInfo_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_DescriptorProto_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_MessageOptions_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_DescriptorProto_ExtensionRange_init_default {false, 0, false, 0, false, google_protobuf_ExtensionRangeOptions_init_default}
#define google_protobuf_DescriptorProto_ReservedRange_init_default {false, 0, false, 0}
#define google_protobuf_ExtensionRangeOptions_init_default {{{NULL}, NULL}, NULL}
#define google_protobuf_FieldDescriptorProto_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _google_protobuf_FieldDescriptorProto_Label_MIN, false, _google_protobuf_FieldDescriptorProto_Type_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_FieldOptions_init_default, false, 0, {{NULL}, NULL}}
#define google_protobuf_OneofDescriptorProto_init_default {{{NULL}, NULL}, false, google_protobuf_OneofOptions_init_default}
#define google_protobuf_EnumDescriptorProto_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_EnumOptions_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_init_default {false, 0, false, 0}
#define google_protobuf_EnumValueDescriptorProto_init_default {{{NULL}, NULL}, false, 0, false, google_protobuf_EnumValueOptions_init_default}
#define google_protobuf_ServiceDescriptorProto_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_ServiceOptions_init_default}
#define google_protobuf_MethodDescriptorProto_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_MethodOptions_init_default, false, false, false, false}
#define google_protobuf_FileOptions_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_FileOptions_OptimizeMode_SPEED, false, false, {{NULL}, NULL}, false, false, false, false, false, false, false, 0, false, false, false, false, false, false, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, false, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define google_protobuf_MessageOptions_init_default {false, false, false, false, false, false, false, 0, {{NULL}, NULL}, NULL}
#define google_protobuf_FieldOptions_init_default {false, google_protobuf_FieldOptions_CType_STRING, false, 0, false, false, false, false, false, google_protobuf_FieldOptions_JSType_JS_NORMAL, false, false, {{NULL}, NULL}, NULL}
#define google_protobuf_OneofOptions_init_default {{{NULL}, NULL}, NULL}
#define google_protobuf_EnumOptions_init_default {false, 0, false, false, {{NULL}, NULL}, NULL}
#define google_protobuf_EnumValueOptions_init_default {false, false, {{NULL}, NULL}, NULL}
#define google_protobuf_ServiceOptions_init_default {false, false, {{NULL}, NULL}, NULL}
#define google_protobuf_MethodOptions_init_default {false, false, false, google_protobuf_MethodOptions_IdempotencyLevel_IDEMPOTENCY_UNKNOWN, {{NULL}, NULL}, NULL}
#define google_protobuf_UninterpretedOption_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_UninterpretedOption_NamePart_init_default {{{NULL}, NULL}, 0}
#define google_protobuf_SourceCodeInfo_init_default {{{NULL}, NULL}}
#define google_protobuf_SourceCodeInfo_Location_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_GeneratedCodeInfo_init_default {{{NULL}, NULL}}
#define google_protobuf_GeneratedCodeInfo_Annotation_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define google_protobuf_FileDescriptorSet_init_zero {{{NULL}, NULL}}
#define google_protobuf_FileDescriptorProto_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_FileOptions_init_zero, false, google_protobuf_SourceCodeInfo_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_DescriptorProto_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_MessageOptions_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_DescriptorProto_ExtensionRange_init_zero {false, 0, false, 0, false, google_protobuf_ExtensionRangeOptions_init_zero}
#define google_protobuf_DescriptorProto_ReservedRange_init_zero {false, 0, false, 0}
#define google_protobuf_ExtensionRangeOptions_init_zero {{{NULL}, NULL}, NULL}
#define google_protobuf_FieldDescriptorProto_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _google_protobuf_FieldDescriptorProto_Label_MIN, false, _google_protobuf_FieldDescriptorProto_Type_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_FieldOptions_init_zero, false, 0, {{NULL}, NULL}}
#define google_protobuf_OneofDescriptorProto_init_zero {{{NULL}, NULL}, false, google_protobuf_OneofOptions_init_zero}
#define google_protobuf_EnumDescriptorProto_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_EnumOptions_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_init_zero {false, 0, false, 0}
#define google_protobuf_EnumValueDescriptorProto_init_zero {{{NULL}, NULL}, false, 0, false, google_protobuf_EnumValueOptions_init_zero}
#define google_protobuf_ServiceDescriptorProto_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_ServiceOptions_init_zero}
#define google_protobuf_MethodDescriptorProto_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_MethodOptions_init_zero, false, 0, false, 0}
#define google_protobuf_FileOptions_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}, false, _google_protobuf_FileOptions_OptimizeMode_MIN, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define google_protobuf_MessageOptions_init_zero {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, NULL}
#define google_protobuf_FieldOptions_init_zero   {false, _google_protobuf_FieldOptions_CType_MIN, false, 0, false, 0, false, 0, false, _google_protobuf_FieldOptions_JSType_MIN, false, 0, {{NULL}, NULL}, NULL}
#define google_protobuf_OneofOptions_init_zero   {{{NULL}, NULL}, NULL}
#define google_protobuf_EnumOptions_init_zero    {false, 0, false, 0, {{NULL}, NULL}, NULL}
#define google_protobuf_EnumValueOptions_init_zero {false, 0, {{NULL}, NULL}, NULL}
#define google_protobuf_ServiceOptions_init_zero {false, 0, {{NULL}, NULL}, NULL}
#define google_protobuf_MethodOptions_init_zero  {false, 0, false, _google_protobuf_MethodOptions_IdempotencyLevel_MIN, {{NULL}, NULL}, NULL}
#define google_protobuf_UninterpretedOption_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_UninterpretedOption_NamePart_init_zero {{{NULL}, NULL}, 0}
#define google_protobuf_SourceCodeInfo_init_zero {{{NULL}, NULL}}
#define google_protobuf_SourceCodeInfo_Location_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_GeneratedCodeInfo_init_zero {{{NULL}, NULL}}
#define google_protobuf_GeneratedCodeInfo_Annotation_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_ExtensionRangeOptions_uninterpreted_option_tag 999
#define google_protobuf_FileDescriptorSet_file_tag 1
#define google_protobuf_GeneratedCodeInfo_annotation_tag 1
#define google_protobuf_OneofOptions_uninterpreted_option_tag 999
#define google_protobuf_SourceCodeInfo_location_tag 1
#define google_protobuf_SourceCodeInfo_Location_path_tag 1
#define google_protobuf_SourceCodeInfo_Location_span_tag 2
#define google_protobuf_SourceCodeInfo_Location_leading_comments_tag 3
#define google_protobuf_SourceCodeInfo_Location_trailing_comments_tag 4
#define google_protobuf_SourceCodeInfo_Location_leading_detached_comments_tag 6
#define google_protobuf_DescriptorProto_ExtensionRange_start_tag 1
#define google_protobuf_DescriptorProto_ExtensionRange_end_tag 2
#define google_protobuf_DescriptorProto_ExtensionRange_options_tag 3
#define google_protobuf_DescriptorProto_ReservedRange_start_tag 1
#define google_protobuf_DescriptorProto_ReservedRange_end_tag 2
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_start_tag 1
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_end_tag 2
#define google_protobuf_EnumOptions_allow_alias_tag 2
#define google_protobuf_EnumOptions_deprecated_tag 3
#define google_protobuf_EnumOptions_uninterpreted_option_tag 999
#define google_protobuf_EnumValueOptions_deprecated_tag 1
#define google_protobuf_EnumValueOptions_uninterpreted_option_tag 999
#define google_protobuf_FieldOptions_ctype_tag   1
#define google_protobuf_FieldOptions_packed_tag  2
#define google_protobuf_FieldOptions_jstype_tag  6
#define google_protobuf_FieldOptions_lazy_tag    5
#define google_protobuf_FieldOptions_deprecated_tag 3
#define google_protobuf_FieldOptions_weak_tag    10
#define google_protobuf_FieldOptions_uninterpreted_option_tag 999
#define google_protobuf_FileOptions_java_package_tag 1
#define google_protobuf_FileOptions_java_outer_classname_tag 8
#define google_protobuf_FileOptions_java_multiple_files_tag 10
#define google_protobuf_FileOptions_java_generate_equals_and_hash_tag 20
#define google_protobuf_FileOptions_java_string_check_utf8_tag 27
#define google_protobuf_FileOptions_optimize_for_tag 9
#define google_protobuf_FileOptions_go_package_tag 11
#define google_protobuf_FileOptions_cc_generic_services_tag 16
#define google_protobuf_FileOptions_java_generic_services_tag 17
#define google_protobuf_FileOptions_py_generic_services_tag 18
#define google_protobuf_FileOptions_php_generic_services_tag 42
#define google_protobuf_FileOptions_deprecated_tag 23
#define google_protobuf_FileOptions_cc_enable_arenas_tag 31
#define google_protobuf_FileOptions_objc_class_prefix_tag 36
#define google_protobuf_FileOptions_csharp_namespace_tag 37
#define google_protobuf_FileOptions_swift_prefix_tag 39
#define google_protobuf_FileOptions_php_class_prefix_tag 40
#define google_protobuf_FileOptions_php_namespace_tag 41
#define google_protobuf_FileOptions_php_metadata_namespace_tag 44
#define google_protobuf_FileOptions_ruby_package_tag 45
#define google_protobuf_FileOptions_uninterpreted_option_tag 999
#define google_protobuf_GeneratedCodeInfo_Annotation_path_tag 1
#define google_protobuf_GeneratedCodeInfo_Annotation_source_file_tag 2
#define google_protobuf_GeneratedCodeInfo_Annotation_begin_tag 3
#define google_protobuf_GeneratedCodeInfo_Annotation_end_tag 4
#define google_protobuf_MessageOptions_message_set_wire_format_tag 1
#define google_protobuf_MessageOptions_no_standard_descriptor_accessor_tag 2
#define google_protobuf_MessageOptions_deprecated_tag 3
#define google_protobuf_MessageOptions_map_entry_tag 7
#define google_protobuf_MessageOptions_uninterpreted_option_tag 999
#define google_protobuf_MethodOptions_deprecated_tag 33
#define google_protobuf_MethodOptions_idempotency_level_tag 34
#define google_protobuf_MethodOptions_uninterpreted_option_tag 999
#define google_protobuf_OneofDescriptorProto_name_tag 1
#define google_protobuf_OneofDescriptorProto_options_tag 2
#define google_protobuf_ServiceOptions_deprecated_tag 33
#define google_protobuf_ServiceOptions_uninterpreted_option_tag 999
#define google_protobuf_UninterpretedOption_name_tag 2
#define google_protobuf_UninterpretedOption_identifier_value_tag 3
#define google_protobuf_UninterpretedOption_positive_int_value_tag 4
#define google_protobuf_UninterpretedOption_negative_int_value_tag 5
#define google_protobuf_UninterpretedOption_double_value_tag 6
#define google_protobuf_UninterpretedOption_string_value_tag 7
#define google_protobuf_UninterpretedOption_aggregate_value_tag 8
#define google_protobuf_UninterpretedOption_NamePart_name_part_tag 1
#define google_protobuf_UninterpretedOption_NamePart_is_extension_tag 2
#define google_protobuf_DescriptorProto_name_tag 1
#define google_protobuf_DescriptorProto_field_tag 2
#define google_protobuf_DescriptorProto_extension_tag 6
#define google_protobuf_DescriptorProto_nested_type_tag 3
#define google_protobuf_DescriptorProto_enum_type_tag 4
#define google_protobuf_DescriptorProto_extension_range_tag 5
#define google_protobuf_DescriptorProto_oneof_decl_tag 8
#define google_protobuf_DescriptorProto_options_tag 7
#define google_protobuf_DescriptorProto_reserved_range_tag 9
#define google_protobuf_DescriptorProto_reserved_name_tag 10
#define google_protobuf_EnumDescriptorProto_name_tag 1
#define google_protobuf_EnumDescriptorProto_value_tag 2
#define google_protobuf_EnumDescriptorProto_options_tag 3
#define google_protobuf_EnumDescriptorProto_reserved_range_tag 4
#define google_protobuf_EnumDescriptorProto_reserved_name_tag 5
#define google_protobuf_EnumValueDescriptorProto_name_tag 1
#define google_protobuf_EnumValueDescriptorProto_number_tag 2
#define google_protobuf_EnumValueDescriptorProto_options_tag 3
#define google_protobuf_FieldDescriptorProto_name_tag 1
#define google_protobuf_FieldDescriptorProto_number_tag 3
#define google_protobuf_FieldDescriptorProto_label_tag 4
#define google_protobuf_FieldDescriptorProto_type_tag 5
#define google_protobuf_FieldDescriptorProto_type_name_tag 6
#define google_protobuf_FieldDescriptorProto_extendee_tag 2
#define google_protobuf_FieldDescriptorProto_default_value_tag 7
#define google_protobuf_FieldDescriptorProto_oneof_index_tag 9
#define google_protobuf_FieldDescriptorProto_json_name_tag 10
#define google_protobuf_FieldDescriptorProto_options_tag 8
#define google_protobuf_FileDescriptorProto_name_tag 1
#define google_protobuf_FileDescriptorProto_package_tag 2
#define google_protobuf_FileDescriptorProto_dependency_tag 3
#define google_protobuf_FileDescriptorProto_public_dependency_tag 10
#define google_protobuf_FileDescriptorProto_weak_dependency_tag 11
#define google_protobuf_FileDescriptorProto_message_type_tag 4
#define google_protobuf_FileDescriptorProto_enum_type_tag 5
#define google_protobuf_FileDescriptorProto_service_tag 6
#define google_protobuf_FileDescriptorProto_extension_tag 7
#define google_protobuf_FileDescriptorProto_options_tag 8
#define google_protobuf_FileDescriptorProto_source_code_info_tag 9
#define google_protobuf_FileDescriptorProto_syntax_tag 12
#define google_protobuf_MethodDescriptorProto_name_tag 1
#define google_protobuf_MethodDescriptorProto_input_type_tag 2
#define google_protobuf_MethodDescriptorProto_output_type_tag 3
#define google_protobuf_MethodDescriptorProto_options_tag 4
#define google_protobuf_MethodDescriptorProto_client_streaming_tag 5
#define google_protobuf_MethodDescriptorProto_server_streaming_tag 6
#define google_protobuf_ServiceDescriptorProto_name_tag 1
#define google_protobuf_ServiceDescriptorProto_method_tag 2
#define google_protobuf_ServiceDescriptorProto_options_tag 3

/* Struct field encoding specification for nanopb */
#define google_protobuf_FileDescriptorSet_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  file,              1)
#define google_protobuf_FileDescriptorSet_CALLBACK pb_default_field_callback
#define google_protobuf_FileDescriptorSet_DEFAULT NULL
#define google_protobuf_FileDescriptorSet_file_MSGTYPE google_protobuf_FileDescriptorProto

#define google_protobuf_FileDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   package,           2) \
X(a, CALLBACK, REPEATED, STRING,   dependency,        3) \
X(a, CALLBACK, REPEATED, MESSAGE,  message_type,      4) \
X(a, CALLBACK, REPEATED, MESSAGE,  enum_type,         5) \
X(a, CALLBACK, REPEATED, MESSAGE,  service,           6) \
X(a, CALLBACK, REPEATED, MESSAGE,  extension,         7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  source_code_info,   9) \
X(a, CALLBACK, REPEATED, INT32,    public_dependency,  10) \
X(a, CALLBACK, REPEATED, INT32,    weak_dependency,  11) \
X(a, CALLBACK, OPTIONAL, STRING,   syntax,           12)
#define google_protobuf_FileDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_FileDescriptorProto_DEFAULT NULL
#define google_protobuf_FileDescriptorProto_message_type_MSGTYPE google_protobuf_DescriptorProto
#define google_protobuf_FileDescriptorProto_enum_type_MSGTYPE google_protobuf_EnumDescriptorProto
#define google_protobuf_FileDescriptorProto_service_MSGTYPE google_protobuf_ServiceDescriptorProto
#define google_protobuf_FileDescriptorProto_extension_MSGTYPE google_protobuf_FieldDescriptorProto
#define google_protobuf_FileDescriptorProto_options_MSGTYPE google_protobuf_FileOptions
#define google_protobuf_FileDescriptorProto_source_code_info_MSGTYPE google_protobuf_SourceCodeInfo

#define google_protobuf_DescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  field,             2) \
X(a, CALLBACK, REPEATED, MESSAGE,  nested_type,       3) \
X(a, CALLBACK, REPEATED, MESSAGE,  enum_type,         4) \
X(a, CALLBACK, REPEATED, MESSAGE,  extension_range,   5) \
X(a, CALLBACK, REPEATED, MESSAGE,  extension,         6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           7) \
X(a, CALLBACK, REPEATED, MESSAGE,  oneof_decl,        8) \
X(a, CALLBACK, REPEATED, MESSAGE,  reserved_range,    9) \
X(a, CALLBACK, REPEATED, STRING,   reserved_name,    10)
#define google_protobuf_DescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_DescriptorProto_DEFAULT NULL
#define google_protobuf_DescriptorProto_field_MSGTYPE google_protobuf_FieldDescriptorProto
#define google_protobuf_DescriptorProto_nested_type_MSGTYPE google_protobuf_DescriptorProto
#define google_protobuf_DescriptorProto_enum_type_MSGTYPE google_protobuf_EnumDescriptorProto
#define google_protobuf_DescriptorProto_extension_range_MSGTYPE google_protobuf_DescriptorProto_ExtensionRange
#define google_protobuf_DescriptorProto_extension_MSGTYPE google_protobuf_FieldDescriptorProto
#define google_protobuf_DescriptorProto_options_MSGTYPE google_protobuf_MessageOptions
#define google_protobuf_DescriptorProto_oneof_decl_MSGTYPE google_protobuf_OneofDescriptorProto
#define google_protobuf_DescriptorProto_reserved_range_MSGTYPE google_protobuf_DescriptorProto_ReservedRange

#define google_protobuf_DescriptorProto_ExtensionRange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    start,             1) \
X(a, STATIC,   OPTIONAL, INT32,    end,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           3)
#define google_protobuf_DescriptorProto_ExtensionRange_CALLBACK NULL
#define google_protobuf_DescriptorProto_ExtensionRange_DEFAULT NULL
#define google_protobuf_DescriptorProto_ExtensionRange_options_MSGTYPE google_protobuf_ExtensionRangeOptions

#define google_protobuf_DescriptorProto_ReservedRange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    start,             1) \
X(a, STATIC,   OPTIONAL, INT32,    end,               2)
#define google_protobuf_DescriptorProto_ReservedRange_CALLBACK NULL
#define google_protobuf_DescriptorProto_ReservedRange_DEFAULT NULL

#define google_protobuf_ExtensionRangeOptions_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_ExtensionRangeOptions_CALLBACK pb_default_field_callback
#define google_protobuf_ExtensionRangeOptions_DEFAULT NULL
#define google_protobuf_ExtensionRangeOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_FieldDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   extendee,          2) \
X(a, STATIC,   OPTIONAL, INT32,    number,            3) \
X(a, STATIC,   OPTIONAL, UENUM,    label,             4) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              5) \
X(a, CALLBACK, OPTIONAL, STRING,   type_name,         6) \
X(a, CALLBACK, OPTIONAL, STRING,   default_value,     7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           8) \
X(a, STATIC,   OPTIONAL, INT32,    oneof_index,       9) \
X(a, CALLBACK, OPTIONAL, STRING,   json_name,        10)
#define google_protobuf_FieldDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_FieldDescriptorProto_DEFAULT NULL
#define google_protobuf_FieldDescriptorProto_options_MSGTYPE google_protobuf_FieldOptions

#define google_protobuf_OneofDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           2)
#define google_protobuf_OneofDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_OneofDescriptorProto_DEFAULT NULL
#define google_protobuf_OneofDescriptorProto_options_MSGTYPE google_protobuf_OneofOptions

#define google_protobuf_EnumDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  value,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           3) \
X(a, CALLBACK, REPEATED, MESSAGE,  reserved_range,    4) \
X(a, CALLBACK, REPEATED, STRING,   reserved_name,     5)
#define google_protobuf_EnumDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_EnumDescriptorProto_DEFAULT NULL
#define google_protobuf_EnumDescriptorProto_value_MSGTYPE google_protobuf_EnumValueDescriptorProto
#define google_protobuf_EnumDescriptorProto_options_MSGTYPE google_protobuf_EnumOptions
#define google_protobuf_EnumDescriptorProto_reserved_range_MSGTYPE google_protobuf_EnumDescriptorProto_EnumReservedRange

#define google_protobuf_EnumDescriptorProto_EnumReservedRange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    start,             1) \
X(a, STATIC,   OPTIONAL, INT32,    end,               2)
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_CALLBACK NULL
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_DEFAULT NULL

#define google_protobuf_EnumValueDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, INT32,    number,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           3)
#define google_protobuf_EnumValueDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_EnumValueDescriptorProto_DEFAULT NULL
#define google_protobuf_EnumValueDescriptorProto_options_MSGTYPE google_protobuf_EnumValueOptions

#define google_protobuf_ServiceDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  method,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           3)
#define google_protobuf_ServiceDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_ServiceDescriptorProto_DEFAULT NULL
#define google_protobuf_ServiceDescriptorProto_method_MSGTYPE google_protobuf_MethodDescriptorProto
#define google_protobuf_ServiceDescriptorProto_options_MSGTYPE google_protobuf_ServiceOptions

#define google_protobuf_MethodDescriptorProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   input_type,        2) \
X(a, CALLBACK, OPTIONAL, STRING,   output_type,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           4) \
X(a, STATIC,   OPTIONAL, BOOL,     client_streaming,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     server_streaming,   6)
#define google_protobuf_MethodDescriptorProto_CALLBACK pb_default_field_callback
#define google_protobuf_MethodDescriptorProto_DEFAULT (const pb_byte_t*)"\x28\x00\x30\x00\x00"
#define google_protobuf_MethodDescriptorProto_options_MSGTYPE google_protobuf_MethodOptions

#define google_protobuf_FileOptions_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   java_package,      1) \
X(a, CALLBACK, OPTIONAL, STRING,   java_outer_classname,   8) \
X(a, STATIC,   OPTIONAL, UENUM,    optimize_for,      9) \
X(a, STATIC,   OPTIONAL, BOOL,     java_multiple_files,  10) \
X(a, CALLBACK, OPTIONAL, STRING,   go_package,       11) \
X(a, STATIC,   OPTIONAL, BOOL,     cc_generic_services,  16) \
X(a, STATIC,   OPTIONAL, BOOL,     java_generic_services,  17) \
X(a, STATIC,   OPTIONAL, BOOL,     py_generic_services,  18) \
X(a, STATIC,   OPTIONAL, BOOL,     java_generate_equals_and_hash,  20) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,       23) \
X(a, STATIC,   OPTIONAL, BOOL,     java_string_check_utf8,  27) \
X(a, STATIC,   OPTIONAL, BOOL,     cc_enable_arenas,  31) \
X(a, CALLBACK, OPTIONAL, STRING,   objc_class_prefix,  36) \
X(a, CALLBACK, OPTIONAL, STRING,   csharp_namespace,  37) \
X(a, CALLBACK, OPTIONAL, STRING,   swift_prefix,     39) \
X(a, CALLBACK, OPTIONAL, STRING,   php_class_prefix,  40) \
X(a, CALLBACK, OPTIONAL, STRING,   php_namespace,    41) \
X(a, STATIC,   OPTIONAL, BOOL,     php_generic_services,  42) \
X(a, CALLBACK, OPTIONAL, STRING,   php_metadata_namespace,  44) \
X(a, CALLBACK, OPTIONAL, STRING,   ruby_package,     45) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_FileOptions_CALLBACK pb_default_field_callback
#define google_protobuf_FileOptions_DEFAULT (const pb_byte_t*)"\x48\x01\x50\x00\x80\x01\x00\x88\x01\x00\x90\x01\x00\xb8\x01\x00\xd8\x01\x00\xf8\x01\x00\xd0\x02\x00\x00"
#define google_protobuf_FileOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_MessageOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     message_set_wire_format,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     no_standard_descriptor_accessor,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,        3) \
X(a, STATIC,   OPTIONAL, BOOL,     map_entry,         7) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_MessageOptions_CALLBACK pb_default_field_callback
#define google_protobuf_MessageOptions_DEFAULT (const pb_byte_t*)"\x08\x00\x10\x00\x18\x00\x00"
#define google_protobuf_MessageOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_FieldOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    ctype,             1) \
X(a, STATIC,   OPTIONAL, BOOL,     packed,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,        3) \
X(a, STATIC,   OPTIONAL, BOOL,     lazy,              5) \
X(a, STATIC,   OPTIONAL, UENUM,    jstype,            6) \
X(a, STATIC,   OPTIONAL, BOOL,     weak,             10) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_FieldOptions_CALLBACK pb_default_field_callback
#define google_protobuf_FieldOptions_DEFAULT (const pb_byte_t*)"\x08\x00\x18\x00\x28\x00\x30\x00\x50\x00\x00"
#define google_protobuf_FieldOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_OneofOptions_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_OneofOptions_CALLBACK pb_default_field_callback
#define google_protobuf_OneofOptions_DEFAULT NULL
#define google_protobuf_OneofOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_EnumOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     allow_alias,       2) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,        3) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_EnumOptions_CALLBACK pb_default_field_callback
#define google_protobuf_EnumOptions_DEFAULT (const pb_byte_t*)"\x18\x00\x00"
#define google_protobuf_EnumOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_EnumValueOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,        1) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_EnumValueOptions_CALLBACK pb_default_field_callback
#define google_protobuf_EnumValueOptions_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define google_protobuf_EnumValueOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_ServiceOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,       33) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_ServiceOptions_CALLBACK pb_default_field_callback
#define google_protobuf_ServiceOptions_DEFAULT (const pb_byte_t*)"\x88\x02\x00\x00"
#define google_protobuf_ServiceOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_MethodOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     deprecated,       33) \
X(a, STATIC,   OPTIONAL, UENUM,    idempotency_level,  34) \
X(a, CALLBACK, REPEATED, MESSAGE,  uninterpreted_option, 999) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define google_protobuf_MethodOptions_CALLBACK pb_default_field_callback
#define google_protobuf_MethodOptions_DEFAULT (const pb_byte_t*)"\x88\x02\x00\x90\x02\x00\x00"
#define google_protobuf_MethodOptions_uninterpreted_option_MSGTYPE google_protobuf_UninterpretedOption

#define google_protobuf_UninterpretedOption_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  name,              2) \
X(a, CALLBACK, OPTIONAL, STRING,   identifier_value,   3) \
X(a, STATIC,   OPTIONAL, UINT64,   positive_int_value,   4) \
X(a, STATIC,   OPTIONAL, INT64,    negative_int_value,   5) \
X(a, STATIC,   OPTIONAL, DOUBLE,   double_value,      6) \
X(a, CALLBACK, OPTIONAL, BYTES,    string_value,      7) \
X(a, CALLBACK, OPTIONAL, STRING,   aggregate_value,   8)
#define google_protobuf_UninterpretedOption_CALLBACK pb_default_field_callback
#define google_protobuf_UninterpretedOption_DEFAULT NULL
#define google_protobuf_UninterpretedOption_name_MSGTYPE google_protobuf_UninterpretedOption_NamePart

#define google_protobuf_UninterpretedOption_NamePart_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name_part,         1) \
X(a, STATIC,   REQUIRED, BOOL,     is_extension,      2)
#define google_protobuf_UninterpretedOption_NamePart_CALLBACK pb_default_field_callback
#define google_protobuf_UninterpretedOption_NamePart_DEFAULT NULL

#define google_protobuf_SourceCodeInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  location,          1)
#define google_protobuf_SourceCodeInfo_CALLBACK pb_default_field_callback
#define google_protobuf_SourceCodeInfo_DEFAULT NULL
#define google_protobuf_SourceCodeInfo_location_MSGTYPE google_protobuf_SourceCodeInfo_Location

#define google_protobuf_SourceCodeInfo_Location_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, INT32,    path,              1) \
X(a, CALLBACK, REPEATED, INT32,    span,              2) \
X(a, CALLBACK, OPTIONAL, STRING,   leading_comments,   3) \
X(a, CALLBACK, OPTIONAL, STRING,   trailing_comments,   4) \
X(a, CALLBACK, REPEATED, STRING,   leading_detached_comments,   6)
#define google_protobuf_SourceCodeInfo_Location_CALLBACK pb_default_field_callback
#define google_protobuf_SourceCodeInfo_Location_DEFAULT NULL

#define google_protobuf_GeneratedCodeInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  annotation,        1)
#define google_protobuf_GeneratedCodeInfo_CALLBACK pb_default_field_callback
#define google_protobuf_GeneratedCodeInfo_DEFAULT NULL
#define google_protobuf_GeneratedCodeInfo_annotation_MSGTYPE google_protobuf_GeneratedCodeInfo_Annotation

#define google_protobuf_GeneratedCodeInfo_Annotation_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, INT32,    path,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   source_file,       2) \
X(a, STATIC,   OPTIONAL, INT32,    begin,             3) \
X(a, STATIC,   OPTIONAL, INT32,    end,               4)
#define google_protobuf_GeneratedCodeInfo_Annotation_CALLBACK pb_default_field_callback
#define google_protobuf_GeneratedCodeInfo_Annotation_DEFAULT NULL

extern const pb_msgdesc_t google_protobuf_FileDescriptorSet_msg;
extern const pb_msgdesc_t google_protobuf_FileDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_DescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_DescriptorProto_ExtensionRange_msg;
extern const pb_msgdesc_t google_protobuf_DescriptorProto_ReservedRange_msg;
extern const pb_msgdesc_t google_protobuf_ExtensionRangeOptions_msg;
extern const pb_msgdesc_t google_protobuf_FieldDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_OneofDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_EnumDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_EnumDescriptorProto_EnumReservedRange_msg;
extern const pb_msgdesc_t google_protobuf_EnumValueDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_ServiceDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_MethodDescriptorProto_msg;
extern const pb_msgdesc_t google_protobuf_FileOptions_msg;
extern const pb_msgdesc_t google_protobuf_MessageOptions_msg;
extern const pb_msgdesc_t google_protobuf_FieldOptions_msg;
extern const pb_msgdesc_t google_protobuf_OneofOptions_msg;
extern const pb_msgdesc_t google_protobuf_EnumOptions_msg;
extern const pb_msgdesc_t google_protobuf_EnumValueOptions_msg;
extern const pb_msgdesc_t google_protobuf_ServiceOptions_msg;
extern const pb_msgdesc_t google_protobuf_MethodOptions_msg;
extern const pb_msgdesc_t google_protobuf_UninterpretedOption_msg;
extern const pb_msgdesc_t google_protobuf_UninterpretedOption_NamePart_msg;
extern const pb_msgdesc_t google_protobuf_SourceCodeInfo_msg;
extern const pb_msgdesc_t google_protobuf_SourceCodeInfo_Location_msg;
extern const pb_msgdesc_t google_protobuf_GeneratedCodeInfo_msg;
extern const pb_msgdesc_t google_protobuf_GeneratedCodeInfo_Annotation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_FileDescriptorSet_fields &google_protobuf_FileDescriptorSet_msg
#define google_protobuf_FileDescriptorProto_fields &google_protobuf_FileDescriptorProto_msg
#define google_protobuf_DescriptorProto_fields &google_protobuf_DescriptorProto_msg
#define google_protobuf_DescriptorProto_ExtensionRange_fields &google_protobuf_DescriptorProto_ExtensionRange_msg
#define google_protobuf_DescriptorProto_ReservedRange_fields &google_protobuf_DescriptorProto_ReservedRange_msg
#define google_protobuf_ExtensionRangeOptions_fields &google_protobuf_ExtensionRangeOptions_msg
#define google_protobuf_FieldDescriptorProto_fields &google_protobuf_FieldDescriptorProto_msg
#define google_protobuf_OneofDescriptorProto_fields &google_protobuf_OneofDescriptorProto_msg
#define google_protobuf_EnumDescriptorProto_fields &google_protobuf_EnumDescriptorProto_msg
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_fields &google_protobuf_EnumDescriptorProto_EnumReservedRange_msg
#define google_protobuf_EnumValueDescriptorProto_fields &google_protobuf_EnumValueDescriptorProto_msg
#define google_protobuf_ServiceDescriptorProto_fields &google_protobuf_ServiceDescriptorProto_msg
#define google_protobuf_MethodDescriptorProto_fields &google_protobuf_MethodDescriptorProto_msg
#define google_protobuf_FileOptions_fields &google_protobuf_FileOptions_msg
#define google_protobuf_MessageOptions_fields &google_protobuf_MessageOptions_msg
#define google_protobuf_FieldOptions_fields &google_protobuf_FieldOptions_msg
#define google_protobuf_OneofOptions_fields &google_protobuf_OneofOptions_msg
#define google_protobuf_EnumOptions_fields &google_protobuf_EnumOptions_msg
#define google_protobuf_EnumValueOptions_fields &google_protobuf_EnumValueOptions_msg
#define google_protobuf_ServiceOptions_fields &google_protobuf_ServiceOptions_msg
#define google_protobuf_MethodOptions_fields &google_protobuf_MethodOptions_msg
#define google_protobuf_UninterpretedOption_fields &google_protobuf_UninterpretedOption_msg
#define google_protobuf_UninterpretedOption_NamePart_fields &google_protobuf_UninterpretedOption_NamePart_msg
#define google_protobuf_SourceCodeInfo_fields &google_protobuf_SourceCodeInfo_msg
#define google_protobuf_SourceCodeInfo_Location_fields &google_protobuf_SourceCodeInfo_Location_msg
#define google_protobuf_GeneratedCodeInfo_fields &google_protobuf_GeneratedCodeInfo_msg
#define google_protobuf_GeneratedCodeInfo_Annotation_fields &google_protobuf_GeneratedCodeInfo_Annotation_msg

/* Maximum encoded size of messages (where known) */
/* google_protobuf_FileDescriptorSet_size depends on runtime parameters */
/* google_protobuf_FileDescriptorProto_size depends on runtime parameters */
/* google_protobuf_DescriptorProto_size depends on runtime parameters */
/* google_protobuf_DescriptorProto_ExtensionRange_size depends on runtime parameters */
#define google_protobuf_DescriptorProto_ReservedRange_size 22
/* google_protobuf_ExtensionRangeOptions_size depends on runtime parameters */
/* google_protobuf_FieldDescriptorProto_size depends on runtime parameters */
/* google_protobuf_OneofDescriptorProto_size depends on runtime parameters */
/* google_protobuf_EnumDescriptorProto_size depends on runtime parameters */
#define google_protobuf_EnumDescriptorProto_EnumReservedRange_size 22
/* google_protobuf_EnumValueDescriptorProto_size depends on runtime parameters */
/* google_protobuf_ServiceDescriptorProto_size depends on runtime parameters */
/* google_protobuf_MethodDescriptorProto_size depends on runtime parameters */
/* google_protobuf_FileOptions_size depends on runtime parameters */
/* google_protobuf_MessageOptions_size depends on runtime parameters */
/* google_protobuf_FieldOptions_size depends on runtime parameters */
/* google_protobuf_OneofOptions_size depends on runtime parameters */
/* google_protobuf_EnumOptions_size depends on runtime parameters */
/* google_protobuf_EnumValueOptions_size depends on runtime parameters */
/* google_protobuf_ServiceOptions_size depends on runtime parameters */
/* google_protobuf_MethodOptions_size depends on runtime parameters */
/* google_protobuf_UninterpretedOption_size depends on runtime parameters */
/* google_protobuf_UninterpretedOption_NamePart_size depends on runtime parameters */
/* google_protobuf_SourceCodeInfo_size depends on runtime parameters */
/* google_protobuf_SourceCodeInfo_Location_size depends on runtime parameters */
/* google_protobuf_GeneratedCodeInfo_size depends on runtime parameters */
/* google_protobuf_GeneratedCodeInfo_Annotation_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
