/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "google/protobuf/field_mask.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_FieldMask, google_protobuf_FieldMask, AUTO)



