/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "google/protobuf/source_context.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_SourceContext, google_protobuf_SourceContext, AUTO)



