/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "google/protobuf/struct.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_Struct, google_protobuf_Struct, AUTO)


PB_BIND(google_protobuf_Struct_FieldsEntry, google_protobuf_Struct_FieldsEntry, AUTO)


PB_BIND(google_protobuf_Value, google_protobuf_Value, AUTO)


PB_BIND(google_protobuf_ListValue, google_protobuf_ListValue, AUTO)




