/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "google/protobuf/type.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_Type, google_protobuf_Type, AUTO)


PB_BIND(google_protobuf_Field, google_protobuf_Field, AUTO)


PB_BIND(google_protobuf_Enum, google_protobuf_Enum, AUTO)


PB_BIND(google_protobuf_EnumValue, google_protobuf_EnumValue, AUTO)


PB_BIND(google_protobuf_Option, google_protobuf_Option, AUTO)






