/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_WRAPPERS_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_WRAPPERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _google_protobuf_BytesValue {
    pb_callback_t value;
} google_protobuf_BytesValue;

typedef struct _google_protobuf_StringValue {
    pb_callback_t value;
} google_protobuf_StringValue;

typedef struct _google_protobuf_BoolValue {
    bool value;
} google_protobuf_BoolValue;

typedef struct _google_protobuf_DoubleValue {
    double value;
} google_protobuf_DoubleValue;

typedef struct _google_protobuf_FloatValue {
    float value;
} google_protobuf_FloatValue;

typedef struct _google_protobuf_Int32Value {
    int32_t value;
} google_protobuf_Int32Value;

typedef struct _google_protobuf_Int64Value {
    int64_t value;
} google_protobuf_Int64Value;

typedef struct _google_protobuf_UInt32Value {
    uint32_t value;
} google_protobuf_UInt32Value;

typedef struct _google_protobuf_UInt64Value {
    uint64_t value;
} google_protobuf_UInt64Value;


/* Initializer values for message structs */
#define google_protobuf_DoubleValue_init_default {0}
#define google_protobuf_FloatValue_init_default  {0}
#define google_protobuf_Int64Value_init_default  {0}
#define google_protobuf_UInt64Value_init_default {0}
#define google_protobuf_Int32Value_init_default  {0}
#define google_protobuf_UInt32Value_init_default {0}
#define google_protobuf_BoolValue_init_default   {0}
#define google_protobuf_StringValue_init_default {{{NULL}, NULL}}
#define google_protobuf_BytesValue_init_default  {{{NULL}, NULL}}
#define google_protobuf_DoubleValue_init_zero    {0}
#define google_protobuf_FloatValue_init_zero     {0}
#define google_protobuf_Int64Value_init_zero     {0}
#define google_protobuf_UInt64Value_init_zero    {0}
#define google_protobuf_Int32Value_init_zero     {0}
#define google_protobuf_UInt32Value_init_zero    {0}
#define google_protobuf_BoolValue_init_zero      {0}
#define google_protobuf_StringValue_init_zero    {{{NULL}, NULL}}
#define google_protobuf_BytesValue_init_zero     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_BytesValue_value_tag     1
#define google_protobuf_StringValue_value_tag    1
#define google_protobuf_BoolValue_value_tag      1
#define google_protobuf_DoubleValue_value_tag    1
#define google_protobuf_FloatValue_value_tag     1
#define google_protobuf_Int32Value_value_tag     1
#define google_protobuf_Int64Value_value_tag     1
#define google_protobuf_UInt32Value_value_tag    1
#define google_protobuf_UInt64Value_value_tag    1

/* Struct field encoding specification for nanopb */
#define google_protobuf_DoubleValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define google_protobuf_DoubleValue_CALLBACK NULL
#define google_protobuf_DoubleValue_DEFAULT NULL

#define google_protobuf_FloatValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             1)
#define google_protobuf_FloatValue_CALLBACK NULL
#define google_protobuf_FloatValue_DEFAULT NULL

#define google_protobuf_Int64Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    value,             1)
#define google_protobuf_Int64Value_CALLBACK NULL
#define google_protobuf_Int64Value_DEFAULT NULL

#define google_protobuf_UInt64Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value,             1)
#define google_protobuf_UInt64Value_CALLBACK NULL
#define google_protobuf_UInt64Value_DEFAULT NULL

#define google_protobuf_Int32Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define google_protobuf_Int32Value_CALLBACK NULL
#define google_protobuf_Int32Value_DEFAULT NULL

#define google_protobuf_UInt32Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define google_protobuf_UInt32Value_CALLBACK NULL
#define google_protobuf_UInt32Value_DEFAULT NULL

#define google_protobuf_BoolValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1)
#define google_protobuf_BoolValue_CALLBACK NULL
#define google_protobuf_BoolValue_DEFAULT NULL

#define google_protobuf_StringValue_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   value,             1)
#define google_protobuf_StringValue_CALLBACK pb_default_field_callback
#define google_protobuf_StringValue_DEFAULT NULL

#define google_protobuf_BytesValue_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1)
#define google_protobuf_BytesValue_CALLBACK pb_default_field_callback
#define google_protobuf_BytesValue_DEFAULT NULL

extern const pb_msgdesc_t google_protobuf_DoubleValue_msg;
extern const pb_msgdesc_t google_protobuf_FloatValue_msg;
extern const pb_msgdesc_t google_protobuf_Int64Value_msg;
extern const pb_msgdesc_t google_protobuf_UInt64Value_msg;
extern const pb_msgdesc_t google_protobuf_Int32Value_msg;
extern const pb_msgdesc_t google_protobuf_UInt32Value_msg;
extern const pb_msgdesc_t google_protobuf_BoolValue_msg;
extern const pb_msgdesc_t google_protobuf_StringValue_msg;
extern const pb_msgdesc_t google_protobuf_BytesValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_DoubleValue_fields &google_protobuf_DoubleValue_msg
#define google_protobuf_FloatValue_fields &google_protobuf_FloatValue_msg
#define google_protobuf_Int64Value_fields &google_protobuf_Int64Value_msg
#define google_protobuf_UInt64Value_fields &google_protobuf_UInt64Value_msg
#define google_protobuf_Int32Value_fields &google_protobuf_Int32Value_msg
#define google_protobuf_UInt32Value_fields &google_protobuf_UInt32Value_msg
#define google_protobuf_BoolValue_fields &google_protobuf_BoolValue_msg
#define google_protobuf_StringValue_fields &google_protobuf_StringValue_msg
#define google_protobuf_BytesValue_fields &google_protobuf_BytesValue_msg

/* Maximum encoded size of messages (where known) */
#define google_protobuf_DoubleValue_size         9
#define google_protobuf_FloatValue_size          5
#define google_protobuf_Int64Value_size          11
#define google_protobuf_UInt64Value_size         11
#define google_protobuf_Int32Value_size          11
#define google_protobuf_UInt32Value_size         6
#define google_protobuf_BoolValue_size           2
/* google_protobuf_StringValue_size depends on runtime parameters */
/* google_protobuf_BytesValue_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
